Repository hratx39-blue-ocean/deep-dive, pull requests merged in 2019-03, with the labels that each got.

#41 feat(new script): commitizen added to package-json, run via commit script
  package-lock.json
  package.json
  readme.md
Labels: in progress

#42 docs(commitizen section in readme): added a stub for commitizen
  readme.md
Labels: help wanted, in progress, pull request

#43 feat(package.json): Add nyc as dev-dep to measure non-Jest test coverage
  package-lock.json
  package.json
Labels: in progress

#45 Created Basic File Structure
  db/index.js
Labels: in progress

#46 Added Components Folder to SRC
  client/src/components/PollMap.js
Labels: in progress

#50 Set up testing structure with Mocha/Chai, add test boilerplate
  package.json
  server/package.json
  server/test/api-tests.js
  server/test/test-boilerplate.js
Labels: in progress

#55 Script fix
  .gitignore
  client/package-lock.json
  client/package.json
  package.json
  server/package-lock.json
  server/package.json
Labels: in progress

#56 Database connection
  db/index.js
  knexfile.js
  package-lock.json
  package.json
  server/routes/example.js
  server/server.js
Labels: in progress

#59 Registration Checker Tool Pull Request
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/__tests__/App.test.js
  client/src/__tests__/RegCheckForm.test.js
  client/src/regCheckForm.js
Labels: in progress

#58 Database connection refactor
  db/index.js
  server/server.js
Labels: back end, in progress

#66 #63: Set up server routes folder structure, server tests
  .gitignore
  client/package-lock.json
  package-lock.json
  package.json
  server/package.json
  server/routes/candidates.js
  server/routes/example.js
  server/routes/index.js
  server/server.js
  server/test/api-tests.js
  server/test/test-boilerplate.js
Labels: in progress

#69 create route for candidateInfoPage
  db/index.js
  server/routes/candidateInfoPage.js
  server/routes/candidates.js
  server/routes/index.js
  server/server.js
  server/test/api-tests.js
Labels: in progress

#71 feat(modified: db/index.js): created a route to get all candidate bios
  db/index.js
  server/routes/bios.js
  server/routes/index.js
  server/server.js
  server/test/api-tests.js
Labels: in progress

#70 style(modified: server/routes/policies.js, server/routes/voter.js, server/server.js, db/index.js): Remove comments and console.logs, add formatting for server routes
  db/index.js
  server/routes/candidates.js
  server/routes/index.js
  server/routes/policies.js
  server/routes/voter.js
  server/server.js
  server/test/api-tests.js
Labels: in progress

#72 Voter info detail
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/__tests__/VoterInfoDetail.test.js
  client/src/components/SideBar.js
  client/src/components/VoterInfoDetail.js
  db/index.js
  server/routes/candidates.js
  server/test/api-tests.js
Labels: in progress

#81 Landing page #22
  client/.DS_Store
  client/package-lock.json
  client/package.json
  client/src/.DS_Store
  client/src/App.js
  client/src/__tests__/App.test.js
  client/src/components/LandingPage.css
  client/src/components/LandingPage.js
  client/src/components/SideBar.js
  client/src/components/VoterInfoDetail.js
  client/src/lib/polls.jpg
  client/src/lib/voting.jpg
Labels: in progress

#82 Header #62
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/__tests__/header.test.js
  client/src/header.js
Labels: in progress

#86 fix(modified: knexfile.js) : specify pool size for database connection
  knexfile.js
Labels: in progress

#87 Candidate cards
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/__tests__/CandidateCards.text.js
  client/src/components/CandidateCards.js
  package-lock.json
  package.json
Labels: in progress

#83 Map service v2
  .gitignore
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/__tests__/App.test.js
  client/src/__tests__/RegCheckForm.test.js
  client/src/components/Map.js
  client/src/components/PollMap.js
  client/src/mocklocationdata.js
  client/src/regCheckForm.js
  db/index.js
  knexfile.js
  package-lock.json
  package.json
  server/package-lock.json
  server/package.json
  server/routes/candidates.js
  server/routes/example.js
  server/routes/index.js
  server/server.js
  server/test/api-tests.js
  server/test/test-boilerplate.js
Labels: in progress

#88 Header routes
  client/src/App.js
  client/src/components/header.js
  client/src/components/regCheckForm.js
Labels: in progress

#91 Package lock bug fix
  client/package-lock.json
  package-lock.json
Labels: in progress

#92 fix(package-lock.json (client)): added a closing bracket
  client/package-lock.json
Labels: in progress

#94 Map service v2
  .DS_Store
  client/db.json
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/__tests__/Map.test.js
  client/src/components/PollMap.js
  client/src/components/baseline-place-24px.svg
  client/src/mocklocationdata.js
  package-lock.json
  server/package-lock.json
Labels: in progress

#93 feat(header.js): add the candidates route
  client/src/components/header.js
Labels: in progress

#96 Server client interaction
  .DS_Store
  .gitignore
  client/package-lock.json
  client/src/App.js
  client/src/__tests__/Map.test.js
  server/bin/www
  server/server.js
Labels: in progress

#98 Ref #25. Add CandidateDetail and PolicyBlock
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/__tests__/CandidateDetail.test.js
  client/src/components/CandidateDetail.js
  client/src/components/CandidateDetailComponents/BiographicCard.js
  client/src/components/CandidateDetailComponents/Breadcrumb.js
  client/src/components/CandidateDetailComponents/CandidateDetail.css
  client/src/components/CandidateDetailComponents/CandidatePhoto.js
  client/src/components/CandidateDetailComponents/PolicyBlock.js
  client/src/components/CandidateDetailComponents/PolicyCard.js
  client/src/components/VoterInfoDetail.js
  package.json
  server/server.js
Labels: in progress

#95 Voter ID Laws
  client/package-lock.json
  client/src/App.js
  client/src/__tests__/StateId.test.js
  client/src/__tests__/VoterId.test.js
  client/src/components/LandingPage.js
  client/src/components/stateId.js
  client/src/components/voterId.js
  db/index.js
  package-lock.json
  server/package-lock.json
  server/package.json
  server/routes/example.js
  server/routes/index.js
  server/routes/voter.js
  server/routes/voterId.js
  server/server.js
  server/test/api-tests.js
  server/voterid/Schema.sql
  server/voterid/potusScraper.js
  server/voterid/seeddb.js
Labels: in progress

#99 fix(client/CandidateCards.js and db/index.js): fixed routes to match …
  client/package-lock.json
  client/src/components/CandidateCards.js
  db/index.js
Labels: in progress

#101 fix(server/server.js): added voterId to destructuring
  server/server.js
Labels: in progress

#102 feat(VoterInfoDetail.js): set up routes between voterinfodetail.js
  client/package-lock.json
  client/src/components/VoterInfoDetail.js
Labels: in progress

#105 fix(header.js): removed selectable property from the menu bar
  client/src/components/header.js
Labels: in progress

#106 style(clean-up console logs and unused code):
  client/src/components/stateId.js
Labels: in progress, pull request

#110 Candidate Routes
  client/src/components/CandidateCards.js
  client/src/components/header.js
Labels: in progress

#111 #104 Add support for incoming routing.
  client/src/components/CandidateDetail.js
  client/src/components/CandidateDetailComponents/BiographicCard.js
  db/index.js
  server/routes/bios.js
  server/routes/candidates.js
  server/routes/policies.js
Labels: in progress

#112 build(modified: package.json): create a npm script for pm2 to run on …
  client/package-lock.json
  package-lock.json
  package.json
  server/package-lock.json
Labels: in progress

#114 Candidate routes
  client/src/components/CandidateCards.js
Labels: in progress

#116 Voter route
  client/package-lock.json
  client/src/components/VoterInfoDetail.js
Labels: in progress

#115 Fix Vermin Supreme ID in dictionary
  client/src/components/CandidateDetail.js
Labels: bug, front end, in progress, server

#121 Style: increased visibility
  client/src/components/CandidateDetail.js
  client/src/components/CandidateDetailComponents/BiographicCard.js
  client/src/components/CandidateDetailComponents/PolicyCard.js
Labels: in progress

#134 #122 Fix Beto O'Rourke candidate detail link.
  client/src/components/CandidateDetail.js
Labels: in progress

#155 refactor(moved knexfile.js and DB directory into server directory): m…
  server/db/index.js
  server/knexfile.js
  server/routes/bios.js
  server/routes/candidateInfoPage.js
  server/routes/candidates.js
  server/routes/policies.js
  server/routes/voter.js
  server/routes/voterId.js
  server/server.js
Labels: in progress

#157 fix(component): Clicking on Am I registered on the sidebar no longer …
  client/package-lock.json
  client/src/components/VoterInfoDetail.js
Labels: in progress

#154 Mopping voterid
  client/src/App.js
  client/src/components/stateId.js
  client/src/components/voterId.js
  package-lock.json
  server/routes/bios.js
  server/routes/candidateInfoPage.js
  server/routes/candidates.js
  server/routes/example.js
  server/routes/policies.js
  server/routes/voter.js
  server/routes/voterId.js
Labels: in progress, pull request

#158 Deleted logo
  client/src/logo.svg
Labels: in progress

#160 #139 #140 #141 Sentence casing and file deletions
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/__tests__/RegCheckForm.test.js
  client/src/__tests__/StateId.test.js
  client/src/__tests__/VoterId.test.js
  client/src/__tests__/header.test.js
  client/src/components/CandidateDetail.js
  client/src/components/CandidateDetailComponents/BiographicCard.js
  client/src/components/CandidateDetailComponents/Breadcrumb.js
  client/src/components/CandidateDetailComponents/CandidateDetail.css
  client/src/components/VoterInfoDetail.js
  client/src/components/voterId.js
Labels: in progress

#159 fix(component): Clicking on twitter link and candidate page link open…
  client/src/components/CandidateDetailComponents/BiographicCard.js
Labels: in progress

#162 refactor(Client files with unused imports/variables): Removes unused …
  client/src/components/CandidateCards.js
  client/src/components/LandingPage.js
  client/src/components/SideBar.js
  client/src/components/VoterInfoDetail.js
  client/src/components/voterId.js
Labels: in progress

#163 Removes lingering greater-than symbol
  client/src/components/VoterInfoDetail.js
Labels: in progress

#165 #124: Uninstall dependencies from root package.json to and install in client, server package.json
  client/package-lock.json
  package-lock.json
  package.json
  server/package-lock.json
  server/package.json
Labels: in progress

#166 refactor(database): connected with .env
  .gitignore
  client/package-lock.json
  server/.env_test
  server/knexfile.js
  server/voterid/seeddb.js
Labels: in progress

#168 CandidateCards Router Update
  client/src/components/CandidateCards.js
  client/src/components/CandidateDetail.js
  client/src/components/header.js
Labels: in progress

#170 chore(PolicyBlock.js): Changed title from Adoption to Abortion
  client/src/components/CandidateDetailComponents/PolicyBlock.js
Labels: in progress

#173 Adds ESLint to the app
  .eslintrc.js
  client/package-lock.json
  client/package.json
  package-lock.json
  package.json
  server/.eslintignore
  server/package-lock.json
  server/package.json
Labels: in progress

#200 Front end lint
  client/src/__tests__/App.test.js
  client/src/__tests__/CandidateCards.text.js
  client/src/__tests__/Map.test.js
  client/src/__tests__/RegCheckForm.test.js
  client/src/__tests__/StateId.test.js
  client/src/__tests__/VoterId.test.js
  client/src/__tests__/VoterInfoDetail.test.js
  client/src/components/PollMap.js
  client/src/components/VoterInfoDetail.js
  client/src/components/regCheckForm.js
Labels: in progress

#201 Disallows console.log in Commits
  .eslintrc.js
Labels: in progress

#204 fix(CandidateCards.test.js): Changes name from '...text.js' to '...test.js'
  client/src/__tests__/CandidateCards.test.js
  package.json
Labels: in progress

#206 Server side lint
  client/package-lock.json
  server/routes/index.js
  server/routes/policies.js
  server/routes/voter.js
  server/routes/voterId.js
  server/test/api-tests.js
  server/voterid/potusScraper.js
  server/voterid/seeddb.js
Labels: in progress

#207 refactor(linting all server directory): linting all server directory files that have not been linted yet
  server/db/index.js
  server/knexfile.js
  server/routes/bios.js
  server/routes/candidateInfoPage.js
  server/routes/candidates.js
  server/test/api-tests.js
Labels: in progress

#208 Fixes Linting issues, Changes commit script
  package.json
  server/package-lock.json
  server/package.json
  server/server.js
Labels: in progress

#210 #202 Add env variables for reliability and consistency.
  .gitignore
  .travis.yml
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/__tests__/RegCheckForm.test.js
  client/src/__tests__/StateId.test.js
  client/src/__tests__/VoterId.test.js
  client/src/__tests__/header.test.js
  client/src/components/CandidateCards.js
  client/src/components/CandidateDetail.js
  client/src/components/CandidateDetailComponents/PolicyBlock.js
  client/src/components/PollMap.js
  client/src/components/VoterInfoDetail.js
  client/src/components/stateId.js
  client/src/components/voterId.js
  client/src/serviceWorker.js
  server/test/api-tests.js
Labels: in progress

#213 Voter info refactor
  .travis.yml
  client/package-lock.json
  client/src/App.js
  client/src/components/LandingPage.css
  client/src/components/LandingPage.js
  client/src/components/VoterInfoDetail.js
  client/src/components/voterId.js
  client/src/lib/registration.jpeg
  package-lock.json
  package.json
Labels: in progress

#214 Finishes VoterInfoDetail refactor
  client/src/components/VoterInfoDetail.js
Labels: in progress

#216 refactor(modified: src/App.js, src/components/header.js, /server/server.js): Update server to render 404 error
  client/package-lock.json
  client/src/components/header.js
  server/bin/www
  server/server.js
Labels: in progress

#217 fix(edited config variable in db/index.js): changed config to directl…
  server/db/index.js
Labels: in progress

#218 Refactor style
  client/src/components/CandidateCards.js
  client/src/components/CandidateDetail.js
  client/src/components/LandingPage.css
  client/src/components/LandingPage.js
  client/src/components/PollMap.js
  client/src/components/SideBar.js
  client/src/components/VoterInfoDetail.js
  client/src/components/header.js
  client/src/components/stateId.js
  client/src/components/voterId.js
  server/.env_test
  server/knexfile.js
Labels: in progress

#219 perf(modified: server/server.js): Update 404 error message
  server/server.js
Labels: in progress

#221 style(Home page photos): Change the home page photos
  client/package-lock.json
  client/src/components/LandingPage.js
  client/src/lib/candidates.jpg
  client/src/lib/iVoted.png
Labels: in progress

#222 feat(modified: client/src/components/CandidateCards.js, client/src/components/CandidateDetail.js, client/src/components/VoterInfoDetail.js, client/src/components/header.js)
  client/src/components/CandidateCards.js
  client/src/components/CandidateDetail.js
  client/src/components/VoterInfoDetail.js
  client/src/components/header.js
Labels: in progress

#223 Removes db.json (#137)
  client/db.json
Labels: in progress

#225 Refactored PollMap Component
  client/src/components/PollMap.js
  client/src/components/logo.svg
Labels: in progress

#226 Basic colors
  client/package-lock.json
  client/package.json
  client/src/components/CandidateCards.js
  client/src/components/CandidateDetail.js
  client/src/components/LandingPage.js
  client/src/components/PollMap.js
  client/src/components/SideBar.js
  client/src/components/VoterInfoDetail.js
  client/src/components/header.js
  client/src/components/regCheckForm.js
  client/src/components/stateId.js
  client/src/components/voterId.js
Labels: in progress

#231 fix(Front end env vars): Fix issue with env vars and create-react-app
  client/package-lock.json
  client/src/components/CandidateCards.js
  client/src/components/CandidateDetail.js
  client/src/components/PollMap.js
  client/src/components/stateId.js
  client/src/components/voterId.js
  server/db/index.js
  server/knexfile.js
  server/test/api-tests.js
Labels: in progress
